---
language: node_js
node_js:
  - "6"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm
<<<<<<< HEAD:Pitch.WebApp/Scripts/apps/pitch/.travis.yml
    - $HOME/.cache # includes bowers cache

before_install:
  - npm config set spin false
  - npm install -g bower
  - bower --version
  - npm install phantomjs-prebuilt
  - node_modules/phantomjs-prebuilt/bin/phantomjs --version

install:
  - npm install
  - bower install
=======

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
  - npm config set spin false
>>>>>>> b3a3165... v2.6.1...v3.0.4:.travis.yml

script:
  - npm run lint:js
  - npm test
